### ISSUE TITLE
Can you share the dataset in the experiment？

### ISSUE THREAD

**Issue by marmotxcw** [AoiDragon/HADES#1]

**Comment by AoiDragon** [comment]
Hello @marmotxcw, thank you for your interest in our work!

We haven't included our data in this repository because it contains harmful images that may not be suitable for public display. We are organizing our data and plan to release it through other methods, such as Google Drive.

**Comment by AoiDragon** [comment]
We have released the data.

**Comment by marmotxcw** [comment]
> We have released the data.

Thank
