### ISSUE TITLE
URL to download beaver-7b Evaluator Model

### ISSUE THREAD

**Issue by tpy001** [AoiDragon/HADES#12]
Hi, AoiDragon:

I wanted to bring to your attention that the URL you provided to download the `beaver-7b` evaluator  may be incorrect. It appears that the link leads to a chat model, which is not intended for content moderation.

The original URL in your README is: https://huggingface.co/PKU-Alignment/beaver-7b-v1.0.

However, I found a new URL that seems to be the correct one: https://huggingface.co/PKU-Alignment/beaver-dam-7b.

Could you please confirm this?

Thank you!

Best regards,
tpy001

**Comment by AoiDragon** [comment]
Hi @tpy001 ,

Thank you for catching this! I've updated the README, and the URL should now be correct.

Best,
Yifan
