### ISSUE TITLE
Question about the SD generation process

### ISSUE THREAD

**Issue by zui-jiang** [AoiDragon/HADES#2]
Your work is very excellent.
I would like to know how you create your data, like the prompt of using Stable Diffusion to generate the damage images. And is there any plan to opensource the attack image dataset?

**Comment by AoiDragon** [comment]
Hello @zui-jiang , thank you for your interest in our work!

For your first question, we have included the whole image generation process in our repo. You can find them under `black_box` folder. For the second one, as mentioned in #1 , we plan to open source it in a more suitable way.
